# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

# Offense count: 82
Metrics/AbcSize:
  Max: 231

# Offense count: 15
Metrics/BlockNesting:
  Max: 5

# Offense count: 6
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 653

# Offense count: 30
Metrics/CyclomaticComplexity:
  Max: 48

# Offense count: 152
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 110

# Offense count: 117
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 283

# Offense count: 7
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 1286

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 7

# Offense count: 28
Metrics/PerceivedComplexity:
  Max: 54

# Offense count: 3
Style/AccessorMethodName:
  Exclude:
    - 'src/modules/IUCVTerminal.rb'

# Offense count: 40
Style/Documentation:
  Enabled: false

# Offense count: 1
Style/DoubleNegation:
  Exclude:
    - 'src/include/s390/dasd/dialogs.rb'

# Offense count: 9
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts.
Style/FileName:
  Exclude:
    - 'src/clients/iucvterminal-server.rb'
    - 'src/clients/s390-disk-controller.rb'
    - 'src/modules/DASDController.rb'
    - 'src/modules/Dump.rb'
    - 'src/modules/IUCVTerminal.rb'
    - 'src/modules/IUCVTerminalServer.rb'
    - 'src/modules/OnPanic.rb'
    - 'src/modules/Xpram.rb'
    - 'src/modules/ZFCPController.rb'

# Offense count: 147
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/MethodName:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 11

# Offense count: 19
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/VariableName:
  Exclude:
    - 'src/include/s390/dasd/helps.rb'
    - 'src/include/s390/iucvterminal-server/helps.rb'
    - 'src/include/s390/iucvterminal-server/ui.rb'
    - 'src/include/s390/zfcp/helps.rb'
    - 'src/modules/IUCVTerminal.rb'
    - 'src/modules/IUCVTerminalServer.rb'
    - 'src/modules/OnPanic.rb'

